linux-binary/symexec --goal-file=SeparationLogic/examples/simple_arith/gcd_goal.v --proof-auto-file=SeparationLogic/examples/simple_arith/gcd_proof_auto.v --proof-manual-file=SeparationLogic/examples/simple_arith/gcd_proof_manual.v --coq-logic-path=SimpleC.EE.simple_arith -slp QCP_examples/ SimpleC.EE --input-file=QCP_examples/simple_arith/gcd.c --no-exec-info;
linux-binary/symexec --goal-file=SeparationLogic/examples/simple_arith/exgcd_goal.v --proof-auto-file=SeparationLogic/examples/simple_arith/exgcd_proof_auto.v --proof-manual-file=SeparationLogic/examples/simple_arith/exgcd_proof_manual.v --coq-logic-path=SimpleC.EE.simple_arith -slp QCP_examples/ SimpleC.EE --input-file=QCP_examples/simple_arith/exgcd.c --no-exec-info;
linux-binary/symexec --goal-file=SeparationLogic/examples/simple_arith/Signed_unsigned_test_goal.v --proof-auto-file=SeparationLogic/examples/simple_arith/Signed_unsigned_test_proof_auto.v --proof-manual-file=SeparationLogic/examples/simple_arith/Signed_unsigned_test_proof_manual.v --coq-logic-path=SimpleC.EE.simple_arith -slp QCP_examples/ SimpleC.EE --input-file=QCP_examples/simple_arith/Signed_unsigned_test.c --no-exec-info;
linux-binary/symexec --goal-file=SeparationLogic/examples/simple_arith/abs_goal.v --proof-auto-file=SeparationLogic/examples/simple_arith/abs_proof_auto.v --proof-manual-file=SeparationLogic/examples/simple_arith/abs_proof_manual.v --coq-logic-path=SimpleC.EE.simple_arith -slp QCP_examples/ SimpleC.EE --input-file=QCP_examples/simple_arith/abs.c --no-exec-info;
linux-binary/symexec --goal-file=SeparationLogic/examples/simple_arith/add_goal.v --proof-auto-file=SeparationLogic/examples/simple_arith/add_proof_auto.v --proof-manual-file=SeparationLogic/examples/simple_arith/add_proof_manual.v --coq-logic-path=SimpleC.EE.simple_arith -slp QCP_examples/ SimpleC.EE --input-file=QCP_examples/simple_arith/add.c --no-exec-info;
linux-binary/symexec --goal-file=SeparationLogic/examples/simple_arith/max3_goal.v --proof-auto-file=SeparationLogic/examples/simple_arith/max3_proof_auto.v --proof-manual-file=SeparationLogic/examples/simple_arith/max3_proof_manual.v --coq-logic-path=SimpleC.EE.simple_arith -slp QCP_examples/ SimpleC.EE --input-file=QCP_examples/simple_arith/max3.c --no-exec-info;
linux-binary/symexec --goal-file=SeparationLogic/examples/simple_arith/div_test_goal.v --proof-auto-file=SeparationLogic/examples/simple_arith/div_test_proof_auto.v --proof-manual-file=SeparationLogic/examples/simple_arith/div_test_proof_manual.v --coq-logic-path=SimpleC.EE.simple_arith -slp QCP_examples/ SimpleC.EE --input-file=QCP_examples/simple_arith/div_test.c --no-exec-info;
linux-binary/symexec --goal-file=SeparationLogic/examples/simple_arith/Always_pos_goal.v --proof-auto-file=SeparationLogic/examples/simple_arith/Always_pos_proof_auto.v --proof-manual-file=SeparationLogic/examples/simple_arith/Always_pos_proof_manual.v --coq-logic-path=SimpleC.EE.simple_arith -slp QCP_examples/ SimpleC.EE --input-file=QCP_examples/simple_arith/Always_pos.c --no-exec-info;
linux-binary/symexec --goal-file=SeparationLogic/examples/simple_arith/mul_goal.v --proof-auto-file=SeparationLogic/examples/simple_arith/mul_proof_auto.v --proof-manual-file=SeparationLogic/examples/simple_arith/mul_proof_manual.v --coq-logic-path=SimpleC.EE.simple_arith -slp QCP_examples/ SimpleC.EE --input-file=QCP_examples/simple_arith/mul.c --no-exec-info;
linux-binary/symexec --goal-file=SeparationLogic/examples/poly_sll_goal.v --proof-auto-file=SeparationLogic/examples/poly_sll_proof_auto.v --proof-manual-file=SeparationLogic/examples/poly_sll_proof_manual.v --coq-logic-path=SimpleC.EE -slp QCP_examples/ SimpleC.EE --input-file=QCP_examples/poly_sll.c --no-exec-info;
linux-binary/symexec --goal-file=SeparationLogic/examples/sll_auto_goal.v --proof-auto-file=SeparationLogic/examples/sll_auto_proof_auto.v --proof-manual-file=SeparationLogic/examples/sll_auto_proof_manual.v --coq-logic-path=SimpleC.EE -slp QCP_examples/ SimpleC.EE --input-file=QCP_examples/sll_auto.c --no-exec-info;
linux-binary/symexec --goal-file=SeparationLogic/examples/fieldtest_goal.v --proof-auto-file=SeparationLogic/examples/fieldtest_proof_auto.v --proof-manual-file=SeparationLogic/examples/fieldtest_proof_manual.v --coq-logic-path=SimpleC.EE -slp QCP_examples/ SimpleC.EE --input-file=QCP_examples/fieldtest.c --no-exec-info;
linux-binary/symexec --goal-file=SeparationLogic/examples/sll_goal.v --proof-auto-file=SeparationLogic/examples/sll_proof_auto.v --proof-manual-file=SeparationLogic/examples/sll_proof_manual.v --coq-logic-path=SimpleC.EE -slp QCP_examples/ SimpleC.EE --input-file=QCP_examples/sll.c --no-exec-info;
linux-binary/symexec --goal-file=SeparationLogic/examples/dll_auto_goal.v --proof-auto-file=SeparationLogic/examples/dll_auto_proof_auto.v --proof-manual-file=SeparationLogic/examples/dll_auto_proof_manual.v --coq-logic-path=SimpleC.EE -slp QCP_examples/ SimpleC.EE --input-file=QCP_examples/dll_auto.c --no-exec-info;
linux-binary/symexec --goal-file=SeparationLogic/examples/sll_insert_sort_goal.v --proof-auto-file=SeparationLogic/examples/sll_insert_sort_proof_auto.v --proof-manual-file=SeparationLogic/examples/sll_insert_sort_proof_manual.v --coq-logic-path=SimpleC.EE -slp QCP_examples/ SimpleC.EE --input-file=QCP_examples/sll_insert_sort.c --no-exec-info;
linux-binary/symexec --goal-file=SeparationLogic/examples/dll_queue_goal.v --proof-auto-file=SeparationLogic/examples/dll_queue_proof_auto.v --proof-manual-file=SeparationLogic/examples/dll_queue_proof_manual.v --coq-logic-path=SimpleC.EE -slp QCP_examples/ SimpleC.EE --input-file=QCP_examples/dll_queue.c --no-exec-info;
linux-binary/symexec --goal-file=SeparationLogic/examples/functional_queue_goal.v --proof-auto-file=SeparationLogic/examples/functional_queue_proof_auto.v --proof-manual-file=SeparationLogic/examples/functional_queue_proof_manual.v --coq-logic-path=SimpleC.EE -slp QCP_examples/ SimpleC.EE --input-file=QCP_examples/functional_queue.c --no-exec-info;
linux-binary/symexec --goal-file=SeparationLogic/examples/sll_queue_goal.v --proof-auto-file=SeparationLogic/examples/sll_queue_proof_auto.v --proof-manual-file=SeparationLogic/examples/sll_queue_proof_manual.v --coq-logic-path=SimpleC.EE -slp QCP_examples/ SimpleC.EE --input-file=QCP_examples/sll_queue.c --no-exec-info;
linux-binary/symexec --goal-file=SeparationLogic/examples/sll_merge_goal.v --proof-auto-file=SeparationLogic/examples/sll_merge_proof_auto.v --proof-manual-file=SeparationLogic/examples/sll_merge_proof_manual.v --coq-logic-path=SimpleC.EE -slp QCP_examples/ SimpleC.EE --input-file=QCP_examples/sll_merge.c --no-exec-info;
linux-binary/symexec --goal-file=SeparationLogic/examples/sum_goal.v --proof-auto-file=SeparationLogic/examples/sum_proof_auto.v --proof-manual-file=SeparationLogic/examples/sum_proof_manual.v --coq-logic-path=SimpleC.EE -slp QCP_examples/ SimpleC.EE --input-file=QCP_examples/sum.c --no-exec-info;
linux-binary/symexec --goal-file=SeparationLogic/examples/swap_goal.v --proof-auto-file=SeparationLogic/examples/swap_proof_auto.v --proof-manual-file=SeparationLogic/examples/swap_proof_manual.v --coq-logic-path=SimpleC.EE -slp QCP_examples/ SimpleC.EE --input-file=QCP_examples/swap.c --no-exec-info;
linux-binary/symexec --goal-file=SeparationLogic/examples/bst_insert_goal.v --proof-auto-file=SeparationLogic/examples/bst_insert_proof_auto.v --proof-manual-file=SeparationLogic/examples/bst_insert_proof_manual.v --coq-logic-path=SimpleC.EE -slp QCP_examples/ SimpleC.EE --input-file=QCP_examples/bst_insert.c --no-exec-info;
linux-binary/symexec --goal-file=SeparationLogic/examples/bst_fp_insert_goal.v --proof-auto-file=SeparationLogic/examples/bst_fp_insert_proof_auto.v --proof-manual-file=SeparationLogic/examples/bst_fp_insert_proof_manual.v --coq-logic-path=SimpleC.EE -slp QCP_examples/ SimpleC.EE --input-file=QCP_examples/bst_fp_insert.c --no-exec-info;
linux-binary/symexec --goal-file=SeparationLogic/examples/bst_fp_delete_goal.v --proof-auto-file=SeparationLogic/examples/bst_fp_delete_proof_auto.v --proof-manual-file=SeparationLogic/examples/bst_fp_delete_proof_manual.v --coq-logic-path=SimpleC.EE -slp QCP_examples/ SimpleC.EE --input-file=QCP_examples/bst_fp_delete.c --no-exec-info;
linux-binary/symexec --goal-file=SeparationLogic/examples/bst_insert_rec_goal.v --proof-auto-file=SeparationLogic/examples/bst_insert_rec_proof_auto.v --proof-manual-file=SeparationLogic/examples/bst_insert_rec_proof_manual.v --coq-logic-path=SimpleC.EE -slp QCP_examples/ SimpleC.EE --input-file=QCP_examples/bst_insert_rec.c --no-exec-info;
linux-binary/symexec --goal-file=SeparationLogic/examples/bst_delete_rec_goal.v --proof-auto-file=SeparationLogic/examples/bst_delete_rec_proof_auto.v --proof-manual-file=SeparationLogic/examples/bst_delete_rec_proof_manual.v --coq-logic-path=SimpleC.EE -slp QCP_examples/ SimpleC.EE --input-file=QCP_examples/bst_delete_rec.c --no-exec-info;
linux-binary/symexec --goal-file=SeparationLogic/examples/bst_delete_rec2_goal.v --proof-auto-file=SeparationLogic/examples/bst_delete_rec2_proof_auto.v --proof-manual-file=SeparationLogic/examples/bst_delete_rec2_proof_manual.v --coq-logic-path=SimpleC.EE -slp QCP_examples/ SimpleC.EE --input-file=QCP_examples/bst_delete_rec2.c --no-exec-info;
linux-binary/symexec --goal-file=SeparationLogic/examples/eval_goal.v --proof-auto-file=SeparationLogic/examples/eval_proof_auto.v --proof-manual-file=SeparationLogic/examples/eval_proof_manual.v --coq-logic-path=SimpleC.EE -slp QCP_examples/ SimpleC.EE --input-file=QCP_examples/eval.c --no-exec-info;
linux-binary/symexec --goal-file=SeparationLogic/examples/typeinfer/typeinfer_goal.v --proof-auto-file=SeparationLogic/examples/typeinfer/typeinfer_proof_auto.v --proof-manual-file=SeparationLogic/examples/typeinfer/typeinfer_proof_manual.v -slp QCP_examples/ SimpleC.EE --no-logic-path --input-file=QCP_examples/typeinfer/typeinfer.c --no-exec-info;
linux-binary/symexec --goal-file=SeparationLogic/examples/fme/fme_goal.v --proof-auto-file=SeparationLogic/examples/fme/fme_proof_auto.v --proof-manual-file=SeparationLogic/examples/fme/fme_proof_manual.v -slp QCP_examples/ SimpleC.EE -IQCP_examples/ --no-logic-path --input-file=QCP_examples/fme/fme.c --no-exec-info;
linux-binary/StrategyCheck --strategy-folder-path=SeparationLogic/examples/  --coq-logic-path=SimpleC.EE --input-file=QCP_examples/common.strategies --no-exec-info;
linux-binary/StrategyCheck --strategy-folder-path=SeparationLogic/examples/  --coq-logic-path=SimpleC.EE --input-file=QCP_examples/poly_sll.strategies --no-exec-info;
linux-binary/StrategyCheck --strategy-folder-path=SeparationLogic/examples/  --coq-logic-path=SimpleC.EE --input-file=QCP_examples/sll_shape.strategies --no-exec-info;
linux-binary/StrategyCheck --strategy-folder-path=SeparationLogic/examples/  --coq-logic-path=SimpleC.EE --input-file=QCP_examples/dll_shape.strategies --no-exec-info;
linux-binary/StrategyCheck --strategy-folder-path=SeparationLogic/examples/  --coq-logic-path=SimpleC.EE --input-file=QCP_examples/sll.strategies --no-exec-info;
linux-binary/StrategyCheck --strategy-folder-path=SeparationLogic/examples/  --coq-logic-path=SimpleC.EE --input-file=QCP_examples/dll_queue.strategies --no-exec-info;
linux-binary/StrategyCheck --strategy-folder-path=SeparationLogic/examples/  --coq-logic-path=SimpleC.EE --input-file=QCP_examples/functional_queue.strategies --no-exec-info;
linux-binary/StrategyCheck --strategy-folder-path=SeparationLogic/examples/  --coq-logic-path=SimpleC.EE --input-file=QCP_examples/sll_queue.strategies --no-exec-info;
linux-binary/StrategyCheck --strategy-folder-path=SeparationLogic/examples/  --coq-logic-path=SimpleC.EE --input-file=QCP_examples/int_array.strategies --no-exec-info;
linux-binary/StrategyCheck --strategy-folder-path=SeparationLogic/examples/  --coq-logic-path=SimpleC.EE --input-file=QCP_examples/uint_array.strategies --no-exec-info;
linux-binary/StrategyCheck --strategy-folder-path=SeparationLogic/examples/  --coq-logic-path=SimpleC.EE --input-file=QCP_examples/bst.strategies --no-exec-info;
linux-binary/StrategyCheck --strategy-folder-path=SeparationLogic/examples/  --coq-logic-path=SimpleC.EE --input-file=QCP_examples/bst_fp.strategies --no-exec-info;
linux-binary/StrategyCheck --strategy-folder-path=SeparationLogic/examples/  --coq-logic-path=SimpleC.EE --input-file=QCP_examples/eval.strategies --no-exec-info;
linux-binary/StrategyCheck --strategy-folder-path=SeparationLogic/examples/typeinfer/ --no-logic-path --input-file=QCP_examples/typeinfer/typeinfer.strategies --no-exec-info;
linux-binary/StrategyCheck --strategy-folder-path=SeparationLogic/examples/fme/ --no-logic-path --input-file=QCP_examples/fme/fme.strategies --no-exec-info;

linux-binary/symexec --goal-file=SeparationLogic/examples/avl_insert_goal.v --proof-auto-file=SeparationLogic/examples/avl_insert_proof_auto.v --proof-manual-file=SeparationLogic/examples/avl_insert_proof_manual.v -slp QCP_examples/ SimpleC.EE -IQCP_examples/ --no-logic-path --input-file=QCP_examples/avl_insert.c --no-exec-info;

linux-binary/StrategyCheck --strategy-folder-path=SeparationLogic/examples/  --coq-logic-path=SimpleC.EE --input-file=QCP_examples/avl.strategies --no-exec-info;

linux-binary/StrategyCheck --strategy-folder-path=SeparationLogic/examples/  --coq-logic-path=SimpleC.EE --input-file=QCP_examples/los_sortlink.strategies --no-exec-info;

linux-binary/StrategyCheck --strategy-folder-path=SeparationLogic/examples/  --coq-logic-path=SimpleC.EE --input-file=QCP_examples/char_array.strategies --no-exec-info;

linux-binary/symexec --goal-file=SeparationLogic/examples/LiteOS/Get_Set_Value_goal.v --proof-auto-file=SeparationLogic/examples/LiteOS/Get_Set_Value_proof_auto.v --proof-manual-file=SeparationLogic/examples/LiteOS/Get_Set_Value_proof_manual.v -slp QCP_examples/ SimpleC.EE -IQCP_examples/ --no-logic-path --input-file=QCP_examples/LiteOS/Get_Set_Value.c --no-exec-info;

linux-binary/symexec --goal-file=SeparationLogic/examples/LiteOS/GetSortLinkNextExpireTime_goal.v --proof-auto-file=SeparationLogic/examples/LiteOS/GetSortLinkNextExpireTime_proof_auto.v --proof-manual-file=SeparationLogic/examples/LiteOS/GetSortLinkNextExpireTime_proof_manual.v -slp QCP_examples/ SimpleC.EE -IQCP_examples/ --no-logic-path --input-file=QCP_examples/LiteOS/GetSortLinkNextExpireTime.c --no-exec-info;

linux-binary/symexec --goal-file=SeparationLogic/examples/LiteOS/List_Add_goal.v --proof-auto-file=SeparationLogic/examples/LiteOS/List_Add_proof_auto.v --proof-manual-file=SeparationLogic/examples/LiteOS/List_Add_proof_manual.v -slp QCP_examples/ SimpleC.EE -IQCP_examples/ --no-logic-path --input-file=QCP_examples/LiteOS/List_Add.c --no-exec-info;

linux-binary/symexec --goal-file=SeparationLogic/examples/LiteOS/LOS_ListDelete_goal.v --proof-auto-file=SeparationLogic/examples/LiteOS/LOS_ListDelete_proof_auto.v --proof-manual-file=SeparationLogic/examples/LiteOS/LOS_ListDelete_proof_manual.v -slp QCP_examples/ SimpleC.EE -IQCP_examples/ --no-logic-path --input-file=QCP_examples/LiteOS/LOS_ListDelete.c --no-exec-info;

linux-binary/symexec --goal-file=SeparationLogic/examples/LiteOS/LOS_ListDelInit_goal.v --proof-auto-file=SeparationLogic/examples/LiteOS/LOS_ListDelInit_proof_auto.v --proof-manual-file=SeparationLogic/examples/LiteOS/LOS_ListDelInit_proof_manual.v -slp QCP_examples/ SimpleC.EE -IQCP_examples/ --no-logic-path --input-file=QCP_examples/LiteOS/LOS_ListDelInit.c --no-exec-info;

linux-binary/symexec --goal-file=SeparationLogic/examples/LiteOS/LOS_ListEmpty_goal.v --proof-auto-file=SeparationLogic/examples/LiteOS/LOS_ListEmpty_proof_auto.v --proof-manual-file=SeparationLogic/examples/LiteOS/LOS_ListEmpty_proof_manual.v -slp QCP_examples/ SimpleC.EE -IQCP_examples/ --no-logic-path --input-file=QCP_examples/LiteOS/LOS_ListEmpty.c --no-exec-info;

linux-binary/symexec --goal-file=SeparationLogic/examples/LiteOS/LOS_ListInit_goal.v --proof-auto-file=SeparationLogic/examples/LiteOS/LOS_ListInit_proof_auto.v --proof-manual-file=SeparationLogic/examples/LiteOS/LOS_ListInit_proof_manual.v -slp QCP_examples/ SimpleC.EE -IQCP_examples/ --no-logic-path --input-file=QCP_examples/LiteOS/LOS_ListInit.c --no-exec-info;

linux-binary/symexec --goal-file=SeparationLogic/examples/LiteOS/OsAdd2SortLink_goal.v --proof-auto-file=SeparationLogic/examples/LiteOS/OsAdd2SortLink_proof_auto.v --proof-manual-file=SeparationLogic/examples/LiteOS/OsAdd2SortLink_proof_manual.v -slp QCP_examples/ SimpleC.EE -IQCP_examples/ --no-logic-path --input-file=QCP_examples/LiteOS/OsAdd2SortLink.c --no-exec-info;

linux-binary/symexec --goal-file=SeparationLogic/examples/LiteOS/OsDeleteNodeSortLink_goal.v --proof-auto-file=SeparationLogic/examples/LiteOS/OsDeleteNodeSortLink_proof_auto.v --proof-manual-file=SeparationLogic/examples/LiteOS/OsDeleteNodeSortLink_proof_manual.v -slp QCP_examples/ SimpleC.EE -IQCP_examples/ --no-logic-path --input-file=QCP_examples/LiteOS/OsDeleteNodeSortLink.c --no-exec-info;

linux-binary/symexec --goal-file=SeparationLogic/examples/LiteOS/OsDeleteSortLink_goal.v --proof-auto-file=SeparationLogic/examples/LiteOS/OsDeleteSortLink_proof_auto.v --proof-manual-file=SeparationLogic/examples/LiteOS/OsDeleteSortLink_proof_manual.v -slp QCP_examples/ SimpleC.EE -IQCP_examples/ --no-logic-path --input-file=QCP_examples/LiteOS/OsDeleteSortLink.c --no-exec-info;

linux-binary/symexec --goal-file=SeparationLogic/examples/LiteOS/OsGetNextExpireTime_goal.v --proof-auto-file=SeparationLogic/examples/LiteOS/OsGetNextExpireTime_proof_auto.v --proof-manual-file=SeparationLogic/examples/LiteOS/OsGetNextExpireTime_proof_manual.v -slp QCP_examples/ SimpleC.EE -IQCP_examples/ --no-logic-path --input-file=QCP_examples/LiteOS/OsGetNextExpireTime.c --no-exec-info;

linux-binary/symexec --goal-file=SeparationLogic/examples/LiteOS/OsGetSortLinkAttribute_goal.v --proof-auto-file=SeparationLogic/examples/LiteOS/OsGetSortLinkAttribute_proof_auto.v --proof-manual-file=SeparationLogic/examples/LiteOS/OsGetSortLinkAttribute_proof_manual.v -slp QCP_examples/ SimpleC.EE -IQCP_examples/ --no-logic-path --input-file=QCP_examples/LiteOS/OsGetSortLinkAttribute.c --no-exec-info;
linux-binary/symexec --goal-file=SeparationLogic/examples/LiteOS/OsSortLinkGetNextExpireTime_goal.v --proof-auto-file=SeparationLogic/examples/LiteOS/OsSortLinkGetNextExpireTime_proof_auto.v --proof-manual-file=SeparationLogic/examples/LiteOS/OsSortLinkGetNextExpireTime_proof_manual.v -slp QCP_examples/ SimpleC.EE -IQCP_examples/ --no-logic-path --input-file=QCP_examples/LiteOS/OsSortLinkGetNextExpireTime.c --no-exec-info;
linux-binary/symexec --goal-file=SeparationLogic/examples/LiteOS/OsSortLinkGetRemainTime_goal.v --proof-auto-file=SeparationLogic/examples/LiteOS/OsSortLinkGetRemainTime_proof_auto.v --proof-manual-file=SeparationLogic/examples/LiteOS/OsSortLinkGetRemainTime_proof_manual.v -slp QCP_examples/ SimpleC.EE -IQCP_examples/ --no-logic-path --input-file=QCP_examples/LiteOS/OsSortLinkGetRemainTime.c --no-exec-info;
linux-binary/symexec --goal-file=SeparationLogic/examples/LiteOS/OsSortLinkGetTargetExpireTime_goal.v --proof-auto-file=SeparationLogic/examples/LiteOS/OsSortLinkGetTargetExpireTime_proof_auto.v --proof-manual-file=SeparationLogic/examples/LiteOS/OsSortLinkGetTargetExpireTime_proof_manual.v -slp QCP_examples/ SimpleC.EE -IQCP_examples/ --no-logic-path --input-file=QCP_examples/LiteOS/OsSortLinkGetTargetExpireTime.c --no-exec-info;
linux-binary/symexec --goal-file=SeparationLogic/examples/LiteOS/OsSortLinkInit_goal.v --proof-auto-file=SeparationLogic/examples/LiteOS/OsSortLinkInit_proof_auto.v --proof-manual-file=SeparationLogic/examples/LiteOS/OsSortLinkInit_proof_manual.v -slp QCP_examples/ SimpleC.EE -IQCP_examples/ --no-logic-path --input-file=QCP_examples/LiteOS/OsSortLinkInit.c --no-exec-info;
linux-binary/symexec --goal-file=SeparationLogic/examples/LiteOS/OsSortLinkResponseTimeConvertFreq_goal.v --proof-auto-file=SeparationLogic/examples/LiteOS/OsSortLinkResponseTimeConvertFreq_proof_auto.v --proof-manual-file=SeparationLogic/examples/LiteOS/OsSortLinkResponseTimeConvertFreq_proof_manual.v -slp QCP_examples/ SimpleC.EE -IQCP_examples/ --no-logic-path --input-file=QCP_examples/LiteOS/OsSortLinkResponseTimeConvertFreq.c --no-exec-info;


linux-binary/symexec --goal-file=SeparationLogic/examples/minigmp/gmp_goal.v --proof-auto-file=SeparationLogic/examples/minigmp/gmp_proof_auto.v --proof-manual-file=SeparationLogic/examples/minigmp/gmp_proof_manual.v -IQCP_examples/ -slp QCP_examples/ SimpleC.EE --no-logic-path --input-file=QCP_examples/minigmp/gmp.c --no-exec-info;
linux-binary/symexec --goal-file=SeparationLogic/examples/cnf_trans/cnf_trans_goal.v --proof-auto-file=SeparationLogic/examples/cnf_trans/cnf_trans_proof_auto.v --proof-manual-file=SeparationLogic/examples/cnf_trans/cnf_trans_proof_manual.v -IQCP_examples/ -slp QCP_examples/ SimpleC.EE --no-logic-path --input-file=QCP_examples/cnf_trans/cnf_trans.c --no-exec-info;
linux-binary/symexec --goal-file=SeparationLogic/examples/alpha_equiv/alpha_equiv_goal.v --proof-auto-file=SeparationLogic/examples/alpha_equiv/alpha_equiv_proof_auto.v --proof-manual-file=SeparationLogic/examples/alpha_equiv/alpha_equiv_proof_manual.v -IQCP_examples/ -slp QCP_examples/ SimpleC.EE --no-logic-path --input-file=QCP_examples/alpha_equiv/alpha_equiv.c --no-exec-info;
linux-binary/symexec --goal-file=SeparationLogic/examples/alpha_equiv/subst_goal.v --proof-auto-file=SeparationLogic/examples/alpha_equiv/subst_proof_auto.v --proof-manual-file=SeparationLogic/examples/alpha_equiv/subst_proof_manual.v -IQCP_examples/ -slp QCP_examples/ SimpleC.EE --no-logic-path --input-file=QCP_examples/alpha_equiv/subst.c --no-exec-info;
linux-binary/symexec --goal-file=SeparationLogic/examples/alpha_equiv/thm_apply_goal.v --proof-auto-file=SeparationLogic/examples/alpha_equiv/thm_apply_proof_auto.v --proof-manual-file=SeparationLogic/examples/alpha_equiv/thm_apply_proof_manual.v -IQCP_examples/ -slp QCP_examples/ SimpleC.EE --no-logic-path --input-file=QCP_examples/alpha_equiv/thm_apply.c --no-exec-info;


linux-binary/symexec --goal-file=SeparationLogic/examples/array_auto_goal.v --proof-auto-file=SeparationLogic/examples/array_auto_proof_auto.v --proof-manual-file=SeparationLogic/examples/array_auto_proof_manual.v --coq-logic-path=SimpleC.EE -slp QCP_examples/ SimpleC.EE --input-file=QCP_examples/array_auto.c --no-exec-info;

linux-binary/symexec --goal-file=SeparationLogic/examples/chars_goal.v --proof-auto-file=SeparationLogic/examples/chars_proof_auto.v --proof-manual-file=SeparationLogic/examples/chars_proof_manual.v --coq-logic-path=SimpleC.EE -slp QCP_examples/ SimpleC.EE --input-file=QCP_examples/chars.c --no-exec-info;

linux-binary/StrategyCheck --strategy-folder-path=SeparationLogic/examples/  --coq-logic-path=SimpleC.EE --input-file=QCP_examples/safeexec.strategies --no-exec-info;

linux-binary/StrategyCheck --strategy-folder-path=SeparationLogic/examples/  --coq-logic-path=SimpleC.EE --input-file=QCP_examples/array_shape.strategies --no-exec-info;

linux-binary/StrategyCheck --strategy-folder-path=SeparationLogic/examples/  --coq-logic-path=SimpleC.EE --input-file=QCP_examples/undef_uint_array.strategies --no-exec-info;

linux-binary/symexec --goal-file=SeparationLogic/examples/int_array_merge_rel_goal.v --proof-auto-file=SeparationLogic/examples/int_array_merge_rel_proof_auto.v --proof-manual-file=SeparationLogic/examples/int_array_merge_rel_proof_manual.v --coq-logic-path=SimpleC.EE -slp QCP_examples/ SimpleC.EE --input-file=QCP_examples/int_array_merge_rel.c --no-exec-info;

linux-binary/symexec --goal-file=SeparationLogic/examples/sll_merge_rel_goal.v --proof-auto-file=SeparationLogic/examples/sll_merge_rel_proof_auto.v --proof-manual-file=SeparationLogic/examples/sll_merge_rel_proof_manual.v --coq-logic-path=SimpleC.EE -slp QCP_examples/ SimpleC.EE --input-file=QCP_examples/sll_merge_rel.c --no-exec-info;

linux-binary/symexec --goal-file=SeparationLogic/examples/sll_split_while_goal.v --proof-auto-file=SeparationLogic/examples/sll_split_while_proof_auto.v --proof-manual-file=SeparationLogic/examples/sll_split_while_proof_manual.v --coq-logic-path=SimpleC.EE -slp QCP_examples/ SimpleC.EE --input-file=QCP_examples/sll_split_while.c --no-exec-info;

linux-binary/symexec --goal-file=SeparationLogic/examples/kmp_rel_goal.v --proof-auto-file=SeparationLogic/examples/kmp_rel_proof_auto.v --proof-manual-file=SeparationLogic/examples/kmp_rel_proof_manual.v --coq-logic-path=SimpleC.EE -slp QCP_examples/ SimpleC.EE --input-file=QCP_examples/kmp_rel.c --no-exec-info;

linux-binary/StrategyCheck --strategy-folder-path=SeparationLogic/examples/  --coq-logic-path=SimpleC.EE --input-file=QCP_examples/safeexecE.strategies --no-exec-info;

echo "All tests finished";