From SimpleC.EE.LLM_friendly_cases Require Import safeexecE_strategy_goal safeexecE_strategy_proof.

Module safeexecE_Strategy_Correctness : safeexecE_Strategy_Correct.
  Include safeexecE_strategy_proof.
End safeexecE_Strategy_Correctness.
